# Starter pipeline
trigger:
- main
steps:
- task: JFrogNuGet@1
  inputs:
    command: 'restore'
    artifactoryConnection: 'sarangeplus'
    targetResolveRepo: 'test-nuget'
    solutionPath: '**/*.sln'
    collectBuildInfo: true
    projectKey: azure

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'PublishProfile'
    PublishProfilePath: '$(System.DefaultWorkingDirectory)/**/*.pubxml'
    PublishProfilePassword: 'Password1e+'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'sarangeplus'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    projectKey: azure
  
- task: JFrogNuGet@1
  inputs:
    command: 'push'
    artifactoryConnection: 'sarangeplus'
    targetDeployRepo: 'test-nuget'
    targetDeployPath: 'azure-test'
    pathToNupkg: '*.nupkg'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    projectKey: azure