# Starter pipeline
trigger:
- main
steps:
- task: JFrogNuGet@1
  inputs:
    command: 'restore'
    artifactoryConnection: 'sarangeplus'
    targetResolveRepo: 'test-nuget'
    solutionPath: '**/*.sln'
    collectBuildInfo: true
    projectKey: nuget

