trigger:
- main
steps:
- task: JFrogNuGet@1
  inputs:
    command: 'restore'
    artifactoryConnection: 'sarangeplus'
    targetResolveRepo: 'test-nuget'
    solutionPath: '**/*.sln'
    collectBuildInfo: true
    projectKey: nuget
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'

- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'sarangeplus'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
  
- task: JFrogNuGet@1
  inputs:
    command: 'push'
    artifactoryConnection: 'sarangeplus'
    targetDeployRepo: 'test-nuget'
    targetDeployPath: 'azure-test'
    pathToNupkg: '*.nupkg'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    projectKey: 'nuget'