trigger:
- main
steps:
- task: JFrogNpm@1

  displayName: 'npm i (Artifactory connection)'

  inputs:

    command: 'install'

    artifactoryConnection: 'sarangeplus'

    sourceRepo: 'npm-virtual'

    workingFolder: '.'