trigger:
- main
steps:
- task: JFrogNuGet@1
  inputs:
    command: 'restore'
    artifactoryConnection: 'sarangeplus'
    targetResolveRepo: 'nuget-virtual'
    solutionPath: '**/*.sln'
    noNuGetCache: true
    nugetProtocolVersion: v3
    