trigger:
- main

steps:
- task: JFrogToolsInstaller@1
  inputs:
    artifactoryConnection: 'sarangeplus'
    cliInstallationRepo: 'jfrog-cli-remote'
    installExtractors: true
    extractorsInstallationRepo: 'extractors'    
- task: JFrogCollectIssues@1
  inputs:
    artifactoryConnection: 'sarangeplus'
    configSource: 'taskConfiguration'
    buildName: 'bmp-nuget-demo'
    buildNumber: '1'
    workingDirectory: './Strike.Core.Infrastructure'